### ISSUE TITLE
Can't find theme file

### ISSUE THREAD

**Issue by pbolger** [rdallasgray/graphene#32]
This is really embarrassing, but try as I might I can't get this theme to load.  
I've managed to install the theme but keep getting this error when I try to load-theme

` signal(error ("Unable to find theme file for `graphene'"))
  error("Unable to find theme file for `%s'" graphene)`

... as you can probably tell I'm a complete novice on Emacs.

**Comment by rdallasgray** [comment]
Hi Paul - can you show me the code which raises this error?

**Comment by pbolger** [comment]
Hi Robert,

  

My graphene plugin is in .emacs.d/elpa/ (There's a graphene and a graphene-
meta-theme in there).

  

My init.l file:

  

;; Require Emacs' package functionality  
(require 'package)  
(package-initialize)  
  
;; Add the Melpa repository to the list of package sources  
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)  
(add-to-list 'load-path "/home/pbolger/.emacs.d/elpha")  
(load-theme 'graphene-meta)  
  
(require 'graphene)  

  

And running 'load-theme' within Emacs gives me this output:

  

Debugger entered--Lisp error: (error "Unable to find theme file for
`graphene'")  
 signal(error ("Unable to find theme file for `graphene'"))  
 error("Unable to find theme file for `%s'" graphene)  
 load-theme(graphene nil nil)  
 call-interactively(load-theme record nil)  
 command-execute(load-theme record)  
 execute-extended-command(nil "load-theme")  
 call-interactively(execute-extended-command nil nil)  

  

  

  

Paul Bolger  

On May 19 2016, at 12:00 am, Robert Dallas Gray
&lt;notifications@github.com&gt; wrote:  

> Hi Paul - can you show me the code which raises this error?

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/rdallas
gray/graphene/issues/32#issuecomment-220005252)![](https://github.com/notifica
tions/beacon/AAAe0J5IZ1lXSfVLMOKM045D23IlhoJ_ks5qCv9TgaJpZM4Igx7M.gif)

**Comment by rdallasgray** [comment]
Hi Paul,

OK, there's a few things in there that don't look quite right. Certainly you shouldn't need to be doing anything with the `graphene-meta` theme; graphene will do that for you. And I don't think you should need to add the `elpa` directory to your load path either.

It looks to me like you might have an older version of graphene there -- it's trying to load a theme called `graphene`, which doesn't exist in the most recent version. Did you download it from Melpa, using `list-packages`?

**Comment by pbolger** [comment]
The graphene folder in elpa is called graphene-20151108.2340.

I went through the steps in the readme file - although the Emacs way of doing things is a bit unfamiliar so I may have misunderstood some of the steps.

**Comment by rdallasgray** [comment]
Hmm, OK. I'm not sure what's happening here. Can you try something for me?

1. Create a new folder in your home folder called `emacs-test`
2. Inside that folder create a folder `.emacs.d`
3. Inside `.emacs.d`, create a file `init.el`
4. Make `init.el` look like this:
```lisp
;; Require Emacs' package functionality
(require 'package)

;; Add the Melpa repository to the list of package sources
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)

;; Initialise the package system.
(package-initialize)
```
5. Run this command: `HOME=~/emacs-test emacs`
6. In Emacs, run `M-x list-packages`
7. Select the line listing graphene from melpa and press `i`
8. Press `x`
9. At the end of your `init.el` file add `(require 'graphene)`
10. Restart Emacs

What this does is create a completely clean Emacs configuration so you're starting effectively from scratch, and we can rule out problems with your own configuration. I just ran all this and didn't get the issue you're raising, so I suspect the problem *is* with your own config. If that's the case, you can use the steps above to help you debug what might be wrong as well -- just gradually add stuff from your own `init.el` to the test `init.el` until something breaks.

Hope that helps -- I'm closing this now as I think it's not a graphene-specific issue. Feel free to reopen it if you find out otherwise.
